typography_spectrum: 0.5448102634400129
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.33470163960009813
  lightness: 0.1531118042767048
  saturation: 0.8118621869944036
  rhythmicContrast: 0.14458609325811267
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7455589608289301
analytics:
  google: null
  facebook: null
  twitter: null
name: samuel kwok bio
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
